### ISSUE TITLE
Обработка тега deleted_offer

### ISSUE THREAD

**Issue by user50** [user50/description-modifier#1]
Сделать так чтобы офферы типа delited скрипт обрабатывал.
вот какие данные в таких офферах должны быть обязательно:

``` html
<categoryId>0</categoryId><currencyId>RUR</currencyId><description></description><name>Удалено</name><model>Удалено</model><price>10000</price><url>http://kupi-na-dom.ru</url><vendor></vendor></offer>
```

в том варианте, где оффер удаленный в прайсе представлен в виде:

``` html
<offer deleted="true" id="161723"/>
```

я вначале меняю offer deleted="true" на offer available="", 
потом /> заменяю на >

``` html
<categoryId>0</categoryId><currencyId>RUR</currencyId><description></description><name>Удалено</name><model>Удалено</model><price>10000</price><url>http://kupi-na-dom.ru</url><vendor></vendor></offer>
```

Делаю все это до запуска скрипта, чтобы потом к ID офферов добавились модификаторы.

там, где оффер представлен в виде:

``` html
<deleted_offers>
<offer id="1961051" />
</deleted_offers>
```

вначале удаляю <deleted_offers> и </deleted_offers>
потом добавляю available=""
потом, как и в предыдущем случае, меняю /> на нужные нам параметры.

 так же в следующую версию модификатора прошу добавить автозамену available="false" на available="" и <price>0</price> на <price>10000</price> , а так же удаление слов опт и оптом в любом регистре

Задача не сложная вроде? сколько накинуть за нее нужно?

**Comment by user50** [comment]
Нужно сюда прикрепить хмл документ где присутствуют все типы офферов

**Comment by proyuri** [comment]
Вот ссылка на файл: https://yadi.sk/d/EcSLYbV0kgMoq

**Comment by proyuri** [comment]
Вот актуальный текст для добавления (скину в чат, некорректно вставляется)

В конфиг нужно добавить возможность указать ID категории для вставки здесь в categoryId

**Comment by EvgenLozov** [comment]
цена - 40уе

сделаем до среды (16.12)

**Comment by proyuri** [comment]
Хорошо!

**Comment by user50** [comment]
В случае когда скрипт должен поделить офферы, что делать с оферами в <deleted_offers>? скопировать их в все файлы или только в один?

**Comment by proyuri** [comment]
не понял вопрос

**Comment by user50** [comment]
В скрипта присутствует возможность делить оферы. как делить оферы которые находятся между элементами deleted_offers

**Comment by proyuri** [comment]
да без разницы в принципе

**Comment by user50** [comment]
> так же в следующую версию модификатора прошу добавить автозамену ... и 0 на 10000 

Нужно пояснения что это означает, заменить 0 на 10000

**Comment by user50** [comment]
> а так же удаление слов опт и оптом в любом регистре

везде или в каких то конкретных тегах?

**Comment by proyuri** [comment]
> а так же удаление слов опт и оптом в любом регистре
> 
> > везде или в каких то конкретных тегах?

в названии и описании

> так же в следующую версию модификатора прошу добавить автозамену ... и 0 на 10000
> 
> > Нужно пояснения что это означает, заменить 0 на 10000

речь идет о цене. Там где указана нулевая цена, меняем на 10000

**Comment by user50** [comment]
Допустим в описании присутствует слово "оптимально". После операции удаления фрагмента "опт" мы получим "имально". Это терпимо?

**Comment by proyuri** [comment]
ну если удалять только целые слова проблематично, то терпимо.

**Comment by proyuri** [comment]
вот в этом коде: 
`<categoryId>0</categoryId><currencyId>RUR</currencyId><description></description><name>Удалено</name><model>Удалено</model><price>10000</price><url>http://kupi-na-dom.ru</url><vendor></vendor></offer>`
который мы вставляем в офферы delited, нужно вынести значение тега categoryId в конфиг. Где-то я писал об этом.

Смысл в том, что определяется отдельная папка на сайте под удаленные офферы, здесь задается id папки, он может быть разный.

**Comment by proyuri** [comment]
так же проблема с кодировкой в кирилице при обработке тега delited в прайсе с кодировкой Windows-1251 (с utf-8 не проверял еще).

**Comment by proyuri** [comment]
`<deleted_offers>
</deleted_offers>`
не удалены.

**Comment by proyuri** [comment]
оказывается, проблема с кририллицей и в других офферах есть, но не везде почему-то. Например, model может быть с ошибкой, а description нормально

**Comment by user50** [comment]
deleted_offers должны быть просто удалены или также офферы внутри них должны быть перемещены в offers?

**Comment by proyuri** [comment]
сами теги `<deleted_offers> </deleted_offers>`должны быть удалены, а офферы внутри них обработаны по шаблону, который мы с вами согласовали и помещены внутри offers

**Comment by EvgenLozov** [comment]
@proyuri 
интересует статус этой задачи

**Comment by proyuri** [comment]
Вроде работает все. Косяков не наблюдал

**Comment by EvgenLozov** [comment]
здесь закрываю , в связи в перемещением в другой  проект
