### ISSUE TITLE
Настройка предельного размера части итогового прайса

### ISSUE THREAD

**Issue by proyuri** [user50/description-modifier#3]
Нужно добавить настройку предельного размера части итогового прайса, при превышении которого остльные оферы переносятся в новую часть.

Т.е. мы либо указываем кол-во частей, на которые делим файл, лио указываем предельный размер части. Указание одной настройки отключает другую.

**Comment by EvgenLozov** [comment]
стоимость будет - 40 уе

**Comment by proyuri** [comment]
ок

**Comment by EvgenLozov** [comment]
> предельного размера части итогового прайса

предельный размер будет измерятся в байтах или в коли-ве офферов?

**Comment by proyuri** [comment]
кол-ве байт

**Comment by user50** [comment]
Гарантировать размер итогового-прайс листа почти не возможно. Итоговый размер будет отличатся от указаного на плюс минус 500 байт

**Comment by proyuri** [comment]
ок

**Comment by EvgenLozov** [comment]
здесь закрываю , в связи в перемещением в другой  проект
