### ISSUE TITLE
Перенос модификатора на сервер

### ISSUE THREAD

**Issue by proyuri** [user50/description-modifier#4]
Требуется создать серверную версию yml-modifer.

**Comment by EvgenLozov** [comment]
Вы хотите сервер отдельный от сервера для мерджинга ? (2 рядомстоящих сервера)
Или расширить сервер для мерджинга функциями модификатора (то есть по факту будет 1 сервер)?

**Comment by proyuri** [comment]
На данный момент, исходя из задач, удобнее будет делать это отдельным сервером.

**Comment by EvgenLozov** [comment]
Сейчас есть 1 файл для задания параметров модификации (config.propeeties). Нужна ли возможность хранить набор таких настроек, по подобию с конфигами на сервера для мерджа

**Comment by proyuri** [comment]
нужен набор конфигов и набор шаблонов. Один и тот же шаблон может использоваться для нескольких конфигов

**Comment by EvgenLozov** [comment]
Может лучше считать конфигом конфиг + шаблон? Чтоб все настройки для модификации были вместе. Добавим копирование конфига и не будет проблемы создать такой же конфиг , но с какими-то правками

**Comment by proyuri** [comment]
ок

**Comment by EvgenLozov** [comment]
И еще один момент.  
Как насчет файлов для модификаци и результатов работы скрипта? Сейчас это все на жестком диске.
Поскольку это буде сервер, с которым предполагается удаленная работа через веб интерфес, то файл для модификации нужно загружать через некую форму , после завершения работы скрипта нужно иметь возможность скачать архив с результатами работы. Так?

**Comment by proyuri** [comment]
2 варианта: либо файл кладется в папку на сервере и указывается путь к нему, либо указываем url-адрес.
При этом, кстати, надо бы добавить функцию обновления файла по url раз в сутки и, соответственно, запуск скрипта автоматический после обновления.

**Comment by proyuri** [comment]
Результаты кладутся в папку. Для каждого конфига своя папка.

**Comment by proyuri** [comment]
не в архиве. Итоговый прайс должен быть доступен по url-ссылке для испорта.

**Comment by EvgenLozov** [comment]
@proyuri 

> либо файл кладется в папку на сервере и указывается путь к нему

этот файл загрузится по фтп или через веб интерфейс?

**Comment by proyuri** [comment]
ftp

**Comment by EvgenLozov** [comment]
Итого, нужен отдельный сервер для модификатора прайсов со след функционалом:
- возможность просматривать список конфигов, создавать их , редактировать и удалять:
- возможность скопировать конфиг
- конфиг представляет собой список всех настроек + шаблон
- источником прайса для модификации будет файл на диске или url. Если указан url, нужно добавить функцию обновления файла по url раз в сутки и, соответственно, запуск скрипта автоматический после обновления.
- результаты модификации кладутся в папку. Для каждого конфига своя папка.

стоимость 100 уе

**Comment by proyuri** [comment]
ок

**Comment by EvgenLozov** [comment]
здесь закрываю , в связи в перемещением в другой  проект
