### ISSUE TITLE
Для сервера: единая ссылка для конфига

### ISSUE THREAD

**Issue by proyuri** [user50/description-modifier#5]
По мотивам [https://github.com/EvgenLozov/yml-merger-server/issues/11](url):
Если в конфиге задано несколько итоговых файлов, у этих прайсов должна быть единая ссылка, файл по которой через заданный промежуток времени меняется (сначала доступна первая часть, потом вторая и т.д.)

**Comment by EvgenLozov** [comment]
здесь закрываю , в связи в перемещением в другой  проект
